- name: set informations of installed eclipse directory
  set_fact:
    eclipse_install_dir: "{{wowza_dev.eclipse.install_dir ~ '-' ~ eclipse.distro}}"
    eclipse_unpack_dir: "{{ eclipse_install_dir ~ '/eclipse'}}"

- name: create plugins install command
  set_fact:
    plugin_install_command: "{{ eclipse_unpack_dir }}/eclipse -nosplash \
      -application org.eclipse.equinox.p2.director \
      -destination {{ eclipse_unpack_dir}} \
      -p2.os       {{ eclipse.os  }} \
      -p2.ws       {{ eclipse.gui }} \
      -p2.arch     {{ ansible_architecture }}"


- name: install wowza eclipse plugin
  command: "{{ plugin_install_command }} \
    -repository {{ wowza_dev.eclipse.wowza_plugin.repository }} \
    -installIU  {{ wowza_dev.eclipse.wowza_plugin.id }} \
    -tag ansible_install_plugin_wowza_dev"
  args:
    creates: "{{ eclipse_unpack_dir}}/*/{{ wowza_dev.eclipse.wowza_plugin.feature_name }}*"


# @see https://wiki.centos.org/de/TipsAndTricks/MultimediaOnCentOS7
- name: install nux-desktop as repo. It is needed for installation of VLC and ffmpeg.
  yum:
    name: "http://li.nux.ro/download/nux/dextop/el7/x86_64/nux-dextop-release-0-5.el7.nux.noarch.rpm"
- name: install VLC. Will be used to set up a demo stream.
  yum:
    name: vlc
    state: present
- name: install ffmped. Will be used to set up a demo stream.
  yum:
    name: "{{ item }}"
    state: present
  with_items: [ffmpeg ffmpeg-devel]